name: "Tests"

on: [pull_request]

jobs:

  # ok test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template_dir: '.github/PULL_REQUEST_TEMPLATE/'
          mapping: 'prtemplate=prtemplate/,prtemp/'
          default: 'prtemplate'
