---
name: Tests
on:
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          template_dir: '.github/PULL_REQUEST_TEMPLATE/'
          mapping: 'feature=feature/,feat/'
          default: 'feature'
