name: Display PR Template

on:
  pull_request:
    types:
      - opened

jobs:
  display_template:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Read PR template
        id: read-template
        run: |
          echo "::set-output name=template::$(cat .github/PULL_REQUEST_TEMPLATE/prtemplate.md)"
      
      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const template = "${{ steps.read-template.outputs.template }}";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: template
            });
